export const FIVE_MINUTES_IN_MS = 1000 * 60 * 5;
export const FIFTEEN_MINUTES_IN_MS = 1000 * 60 * 15;
export const DEFAULT_PAGINATION_LIMIT = 10;
export const MAX_PAGINATION_LIMIT = 100;
export const DEFAULT_PAGINATION_OFFSET = 0;
